### ISSUE TITLE
Color conversion problem

### ISSUE THREAD

**Issue by tnkarno** [ricokahler/color2k#442] opened 2022-07-08 06:43 UTC
Version: 2.0.0,

Problem: Try to convert a hex to HSLA and back to hex. The expected result is the same hex. (Currently, it's different)
This comes from the `hsla` function. It uses `toFixed()` and it loses the correct value. I think it shouldn't round the values.

**Comment by ricokahler** [comment] 2022-07-11 21:16
Hi I believe this is a duplicate of #211.

I'll close in favor of that but if you have a suggestion on how to improve this, please do share over there 😄. Keep in mind that the output of these colors should be readable by CSS.
In particular, these specs: [rgba](https://drafts.csswg.org/css-color/#rgb-functions) and [hsla](https://drafts.csswg.org/css-color/#funcdef-hsla)

**Closed as completed by ricokahler** 2022-07-11 21:16 UTC
